### ISSUE TITLE
Sustainable Forest Products site

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#102]
https://sustainableforestproducts.org/
would like this site flattened/archived (can we get a cost/time estimate)

Meeting question: What does it mean to flatten a site?
- Save site as is with no additional updates, freeze in time
- We just need an estimate for how much this will be and what it will take
- Maria will research a way for Pantheon to work on it

Would be good for WRI to do this in house so also consider training for Christian and team to take care of.

**Comment by mariacha** [comment]
My initial thought was to use Tome: https://tome.fyi/docs/installing-existing-site/ -- this isn't something we've done before, but it's something we've wanted to do.

I did see that there's a Search form which we'd need to think about (turn off? Use solr still?). Are there any other forms associated with this site?

**Comment by mariacha** [comment]
Update: Sounds like Pantheon doesn't have a great alternative, so we can talk about what Christian tried tomorrow, and see if it's the same thing.

**Comment by monicapatel21** [comment]
from christian in chat:

wget -mpck --user-agent="" -e robots=off --wait 1 -E http://www.developmentalert.org/
wget -mpck --user-agent="" -e robots=off --wait 1 [www.chinafaqs.org](http://www.chinafaqs.org/)

Don't worry about search (ok to disable) 
Once finished, AWS3 configured through CloudFront is an OK solution even though SSL is tricky because it requires the least maintenance we're aware of so far, cost effective for S3 to serve out files.

**Comment by mariacha** [comment]
I tried out the Tome approach because it seemed relatively straightforward. Here's the url it creates:
https://wri-103-sfproducts1.pantheonsite.io/sites/default/files/html/

The entire site can be download here: https://wri-103-sfproducts1.pantheonsite.io/admin/config/tome/static/download and uploaded to another place.

The steps were easy:
1. Install the Tome drupal module. https://www.drupal.org/project/tome
2. Set the export path in the settings.php file
3. Run the Generate command, which can also be done here: https://wri-103-sfproducts1.pantheonsite.io/admin/config/tome/static/generate

I'm running Screaming Frog on the different sites to see what differences there may be, but the actual setup of this was really quick.

**Comment by mariacha** [comment]
VR tests are difficult to run because this is essentially a single-page app, but from my scans, this looks pretty good!

Someone who knows how the site should work should take a look at it, because there are things that feel broken to me, but they're also broken on the live site, like the language switcher doesn't make sense to me...

@StudioZut Are you thinking for hosting, something like this? https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-custom-domain-walkthrough.html

**Comment by monicapatel21** [comment]
Once Nicole gets confirmation that this looks good: https://wri-103-sfproducts1.pantheonsite.io/sites/default/files/html/
re-assign ticket to Christian to do the download and add to AWS3
