### ISSUE TITLE
Robots.txt (Brasil)

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#104]
Make sure this isn't hard-coded

In wri.org it says 

> # Extra robots.txt content, editable from 
> # administration pages (admin/config/search/custom_robots)
> 
> # sitemap
> Sitemap: /sitemap.xml
> (broken path)

Possible that module used at the time for rewriting is what caused the problem, but Maria will investigate and repair

**Comment by shannon-paton** [comment]
URL to be optimized:
https://www.wribrasil.org.br/robots.txt

Built doc with optimized Robots.txt and explanation:
https://docs.google.com/document/d/1mU7Nk26ogtieJ8PTDKtD3sRsVmXoQBqirbhF-Ke3YLw/edit

**Comment by mariacha** [comment]
It looks like https://www.drupal.org/project/robotstxt should work with Pantheon because it takes the approach I was suggesting and hijacks the robots.txt url. We'll have to try it out on a live site though, because of the items noted in https://pantheon.io/docs/bots-and-indexing#indexing-your-pantheon-site:
```
While Drupal and WordPress both generate their own robots.txt file by default, a custom or CMS-standard robots.txt will only work in Live environments of a paid site with a custom domain.
```

It does seem like a pretty low-risk module to add, so we could add it to the install profile and then just install it on deploy (and test out there).

It looks like in D7 the module providing that admin url was https://www.drupal.org/project/custom_robots

**Comment by mariacha** [comment]
@shannon-paton Ready for review on develop. I left instructions in https://github.com/wri/wri_sites/issues/104#issuecomment-1263856572

**Comment by shannon-paton** [comment]
It seems like we can only test this one once it's live &mdash; is that correct @mariacha? @StudioZut flagging for after the deployment to Brasil so that you can add the extra robots.txt content

**Comment by mariacha** [comment]
Yep, that's correct, the additions will have to go onto live directly.

**Comment by shannon-paton** [comment]
Ok! Instructions make sense to me, thanks.

**Comment by mariacha** [comment]
https://www.wribrasil.org.br/admin/config/search/custom-robots exists now. I added some things to it but it doesn't look like they show up:
https://www.wribrasil.org.br/robots.txt

So I'll pull this back and keep investigating

**Comment by mariacha** [comment]
It seems like the path is indeed to delete the robots.txt file from the pantheon repo and then deploy that to live:
https://pantheon-community.slack.com/archives/CTA1621KK/p1628712366058600

But I think we only have to do that once.

Since we have another brasil-centric ticket in https://github.com/wri/wri-brasil/issues/104 I can bundle those together in their own deploy, probably.

**Comment by mariacha** [comment]
I installed the wrong module! I guess that's the risk that comes with putting a lot of links in my notes. This is the right one:
https://www.drupal.org/project/robotstxt

The config for the new module is at https://develop-wri-brasil.pantheonsite.io/admin/config/search/robotstxt and this should definitely work in the next deploy. 

It gets rid of the robots.txt file that comes with Drupal the way the module at  recommends: https://www.drupal.org/project/robotstxt/issues/2832437#comment-14285810

**Comment by shannon-paton** [comment]
Not sure if we can test this one until after deployment, but think this should work!

**Comment by mariacha** [comment]
Ok, this appears to be working:
https://www.wribrasil.org.br/admin/config/search/robotstxt

I added two items that weren't already there:

Disallow: /*page-not-found
Disallow: /en/

And they should show up here now too: https://www.wribrasil.org.br/robots.txt

**Comment by shannon-paton** [comment]
This looks good to me. I've passed along to the Brasil team
