### ISSUE TITLE
Redirects catch

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#94]
## Dev tasks
- [x] Some redirects are to unaliased items, like `/pt/node/43031` which should just redirect to `/node/43031`. There's likely a way to universally redirect those, which I can work on.
- [x] Some redirects, like this one `/pt/publication/8-principios-da-calcada` and `/areascalmas` are trying to find an english version of the content, which doesn't exist on the new site. I can change those english-language redirects to be in Portuguese by default (or possibly und, I'll need to experiment).
- [x] There are some taxonomy term aliases on the old site that should redirect to the new /recursos pages. That's actually an ongoing migration need, which I'll add to the list for the next IO. 
- [x] Add some cleanup scripts to the wri_migration module for brasil (like [this](https://github.com/wri/wri-brasil/blob/develop/web/modules/custom/wri_migration/wri_migration.install#L102)): `DELETE from redirect WHERE redirect_redirect__uri LIKE 'internal:/node/%' AND redirect_redirect__uri NOT IN (SELECT CONCAT('internal:/node/', nid) FROM node);` and could additionally be run for taxonomy terms. Easy enough to figure out, and then move that to the migration README.

**Comment by monicapatel21** [comment]
1. Share the list that WRI Brasil found from SEM Rush -- then assign to Maria (and Monica) to see if this can be added to y/and deployment

2. Go ahead and make manual redirects for any big ones caught now

**Comment by wthomaswri** [comment]
Here is the list @mariacha @monicapatel2
[wri-brasil-pt-broken-links.xlsx](https://github.com/wri/wri_sites/files/9095527/wri-brasil-pt-broken-links.xlsx)
1

**Comment by mariacha** [comment]
Ok, I've gone through this list of links and found a few things that are fixable in code:

1. Some redirects are to unaliased items, like `/pt/node/43031` which should just redirect to `/node/43031`. There's likely a way to universally redirect those, which I can work on.
2. Some redirects, like this one `/pt/publication/8-principios-da-calcada` and `/areascalmas` are trying to find an english version of the content, which doesn't exist on the new site. I can change those english-language redirects to be in Portuguese by default (or possibly und, I'll need to experiment).
3. There are some taxonomy term aliases on the old site that should redirect to the new /recursos pages. That's actually an ongoing migration need, which I'll add to the list for the next IO. 
4. Generally it's probably a good idea to clean up any aliases or redirects that point to nodes or taxonomy terms that were not migrated. I've got a couple queries that I remember running on the flagship site to do this. I'll add these cleanup queries to the general migration instructions, because I didn't remember if they would be relevant for future migrations, or just flagship.

Other observations, that should be fixed using the Admin area:
1. We didn't migrate over blog tags at all: https://d8-migrate-wribrasil.pantheonsite.io/en/admin/structure/taxonomy/blog_categories so those urls should all be redirected manually to whatever feels relevant. In the old site they looked like this: `/pt/blog-tags/10002`
2. Some content was not migrated, so its redirects or aliases pointed to old node ids that don't exist. This covers pages like `/pt/sobre` and some Project pages that were re-created on the new site. Those will need to be manually added as redirects as they pop up.
3. Some of the urls don't resolve on the old site either. Like https://d8-migrate-wribrasil.pantheonsite.io/pt/noticias/LINK so those are fine to stay as 404s. I'm guessing those are in content somewhere on the new site and just need to be cleaned up as part of the work above.

**Comment by wthomaswri** [comment]
Sounds good @mariacha. We'll work on the manual bit and sounds good for the code portion.

**Comment by mariacha** [comment]
I've turned the last checkbox into https://github.com/wri/wri_sites/issues/120 and am cleaning up references to the `blog-tags` in https://github.com/wri/wri-brasil/issues/182 so I'm closing this one.
